FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_API_BASE_URL
ARG VITE_GEMINI_API_KEY
ARG VITE_BILLING_ENABLED
ARG VITE_BILLING_PROVIDER
ARG VITE_PLAY_SUBSCRIPTION_PRODUCT_ID
ARG VITE_PLAY_SUBSCRIPTION_PRODUCT_IDS
ARG VITE_ADMIN_UIDS
ARG VITE_AUTH_DEBUG
ARG VITE_PARTNER_LINK_REQUIRES_PRO
ARG VITE_AI_MAX_OUTPUT_TOKENS
ARG VITE_AI_SUMMARY_MAX_OUTPUT_TOKENS
ARG VITE_AI_TIMEOUT_MS
ARG VITE_AI_CACHE_TTL_MS

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY
ENV VITE_BILLING_ENABLED=$VITE_BILLING_ENABLED
ENV VITE_BILLING_PROVIDER=$VITE_BILLING_PROVIDER
ENV VITE_PLAY_SUBSCRIPTION_PRODUCT_ID=$VITE_PLAY_SUBSCRIPTION_PRODUCT_ID
ENV VITE_PLAY_SUBSCRIPTION_PRODUCT_IDS=$VITE_PLAY_SUBSCRIPTION_PRODUCT_IDS
ENV VITE_ADMIN_UIDS=$VITE_ADMIN_UIDS
ENV VITE_AUTH_DEBUG=$VITE_AUTH_DEBUG
ENV VITE_PARTNER_LINK_REQUIRES_PRO=$VITE_PARTNER_LINK_REQUIRES_PRO
ENV VITE_AI_MAX_OUTPUT_TOKENS=$VITE_AI_MAX_OUTPUT_TOKENS
ENV VITE_AI_SUMMARY_MAX_OUTPUT_TOKENS=$VITE_AI_SUMMARY_MAX_OUTPUT_TOKENS
ENV VITE_AI_TIMEOUT_MS=$VITE_AI_TIMEOUT_MS
ENV VITE_AI_CACHE_TTL_MS=$VITE_AI_CACHE_TTL_MS

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build:production

FROM node:20-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-server ./dist-server

ENV PORT=8080
ENV NODE_ENV=production

EXPOSE 8080

CMD ["node", "dist-server/index.js"]
