// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fampal-redesign/BoldDark.tsx": () => import("../components/mockups/fampal-redesign/BoldDark.tsx"),
  "./components/mockups/fampal-redesign/CleanLight.tsx": () => import("../components/mockups/fampal-redesign/CleanLight.tsx"),
  "./components/mockups/fampal-redesign/PlayfulWarm.tsx": () => import("../components/mockups/fampal-redesign/PlayfulWarm.tsx")
};
